- name: Copy logstash Config File
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  systemd:
    name: logstash
    state: restarted
    enabled: yes
