- name: RoboShop Frontend setup
  hosts: FRONTEND
  tags: frontend
  become: yes
  roles:
    - name: frontend

- name: RoboShop MongoDB setup
  hosts: MONGODB
  tags: mongodb
  become: yes
  roles:
    - name: mongodb
            
