- name: Installing nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Download and Extract Frontend content
  include_role:
    name: common
    tasks_from: download

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copying roboshop config file
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
    enabled: yes













