- name: Installing nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove old content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Download and Extract Frontend content
  include_role:
    name: common
    tasks_from: download

- name: copy the extracted content
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Update Main Nginx Config
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

##- name: copying roboshop config file
##  copy:
##    src: roboshop.conf
##    dest: /etc/nginx/default.d/roboshop.conf

- name: updating roboshop config file
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Install Node Exporter
  include_role:
    name: common
    tasks_from: node-exporter

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Setup Filebeat
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    LOG_FILE: /var/log/nginx/access.log














