- name: Setup mysql repo
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install Mysql Server
  yum:
    name: [ "mysql-community-server", "MySQL-python" ]
    state: present

- name: Start Mysql Server
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: checking password
  community.mysql.mysql_query:
    query: show databases
    login_user: root
    login_password: RoboShop@1
  register: default_mysql_passwd
  ignore_errors: yes
