- name: Setup mysql repo
  copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install Mysql Server
  yum:
    name: [ "mysql-community-server", "MySQL-python" ]
    state: present

- name: Start Mysql Server
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: checking password
  community.mysql.mysql_query:
    query: show databases
    login_user: root
    login_password: RoboShop@1
  register: default_mysql_passwd
  ignore_errors: yes

- name: print
  debug:
    msg: "{{default_mysql_passwd}}"

- name: Grab Default Password
  when: default_mysql_passwd.failed
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: out

- name: Reset Mysql Passwd
  shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p$"{{out.stdout}}"

- name: Uninstall Validate passwd plugin
  community.mysql.mysql_query:
    query: uninstall plugin validate_password
    login_user: root
    login_password: RoboShop@1
  ignore_errors: yes

- name: Download and Extract Frontend content
  include_role:
    name: common
    tasks_from: download

##- name: Load Schema
##  community.mysql.mysql_db:
##    state: import
##    name: all
##    target: /tmp/mysql-main/shipping.sql
##    login_user: root
##    login_password: RoboShop@1
##





