- name: Adding Roboshop Application User
  user:
    name: roboshop

- name: Download From Github
  include_tasks:
    file: download-from-github.yml

- name: Delete Old App Code
  file:
    path: /home/roboshop/{{COMPONENT}}

- name: copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop