- name: Adding Roboshop Application User
  user:
    name: roboshop
  register: app_user

- name: Download From Github
  include_tasks:
    file: download-from-github.yml

- name: Delete Old App Code
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent
  ignore_errors: yes

- name: copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
    owner: roboshop
    group: roboshop