- name: Install Maven
  yum:
    name: maven
    state: installed

- name: Downloading & Extracting App Code & Add User
  include_tasks:
    file: download.yml

- name: Compile The Packges
  shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}

- name: Setup Systemd
  include_tasks:
    file: systemd-setup.yml

- name: Install Node Exporter
  include_tasks:
    file: node-exporter.yml

- name: Running filebeat config
  include_tasks:
    file: filebeat.yml
  vars:
    LOG_FILE: /var/log/{{COMPONENT}}.log
    STRUCTURED: "true"
    APP_TYPE: java



