- name: copy hostname script
  copy:
    src: set-hostname.sh
    dest: /bin/set-hostname
    mode: 0755

- name: setting hostname
  shell: set-hostname {{COMPONENT}}

- name: Update rsyslog Config
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/roboshop.conf

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted