- name: Installing Nodejs
  yum:
    name: [ "nodejs", "make", "gcc-c++"]
    state: present

- name: Downloading & Extracting App Code & Add User
  include_tasks:
    file: download.yml

- name: Installing Nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}/
    state: latest
  become_user: roboshop

- name: Setup Systemd
  include_tasks:
    file: systemd-setup.yml

- name: Install Node Exporter
  include_tasks:
    file: node-exporter.yml

- name: Running filebeat config
  include_tasks:
    file: filebeat.yml
  vars:
    LOG_FILE: /var/log/{{COMPONENT}}.log
    STRUCTURED: "true"
    APP_TYPE: nodejs


