- name: Installing Nodejs
  yum:
    name: [ "nodejs", "make", "gcc-c++"]
    state: present

- name: Downloading & Extracting App Code & Add User
  include_tasks:
    file: download.yml

- name: Installing Nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}/
    state: latest
  become_user: roboshop

- name: Setup Systemd
  include_tasks:
    file: systemd-setup.yml


