- name: Installing Nodejs
  yum:
    name: [ "nodejs", "make", "gcc-c++"]
    state: present

- name: Adding Roboshop Application User
  user:
    name: roboshop

- name: Downloading catalogue component from Github
  include_tasks:
    file: download.yml

- name: copy the extracted content
  copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Installing Nodejs dependencied
  community.general.npm:
    path: /home/roboshop/catalogue/
    state: latest
  become_user: roboshop


